// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAFkN_s59XQMNEVAUzRyds_0ghZRYJu8wk',
    appId: '1:497553706951:web:6a3e8228db243623c4d3e2',
    messagingSenderId: '497553706951',
    projectId: 'care-assist-787d1',
    authDomain: 'care-assist-787d1.firebaseapp.com',
    storageBucket: 'care-assist-787d1.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCVS3fezT3II_yq5w5ysq5G-YXYlV9NWbU',
    appId: '1:497553706951:android:b861c53580c98601c4d3e2',
    messagingSenderId: '497553706951',
    projectId: 'care-assist-787d1',
    storageBucket: 'care-assist-787d1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDoSg4yUGA6hF_HGVqioCLbeXDO48bU1IU',
    appId: '1:497553706951:ios:73acd13da27df738c4d3e2',
    messagingSenderId: '497553706951',
    projectId: 'care-assist-787d1',
    storageBucket: 'care-assist-787d1.firebasestorage.app',
    iosBundleId: 'com.example.careAssist',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAFkN_s59XQMNEVAUzRyds_0ghZRYJu8wk',
    appId: '1:497553706951:web:c8b224e19d26d377c4d3e2',
    messagingSenderId: '497553706951',
    projectId: 'care-assist-787d1',
    authDomain: 'care-assist-787d1.firebaseapp.com',
    storageBucket: 'care-assist-787d1.firebasestorage.app',
  );

}